### ISSUE TITLE
RuntimeError in GAN training

### ISSUE THREAD

**Issue by yuta-tech** [dariopavllo/convmesh#1]
When training GAN with text, an error  happened in function "update_generator_running_avg".
My enviroment is

**OS : Ubuntu 18.04.4 LTS
Python : 3.6.12
Pytorch : 1.6.0
CUDA : 10.1**

The error detail is below,

**Traceback (most recent call last):
  File "run_generation.py", line 713, in <module>
    update_generator_running_avg(epoch)
  File "run_generation.py", line 452, in update_generator_running_avg
    param.mul_(alpha).add_(g_state_dict[k], alpha=1-alpha)
RuntimeError: result type Float can't be cast to the desired output type Long**

And I found type of "param" is changed float32 to long(int64) by print debug in for loop.

**type of param : torch.float32 
type of alpha : <class 'float'>
type of param : torch.float32
type of alpha : <class 'float'>
type of param : torch.float32
type of alpha : <class 'float'>
type of param : torch.float32
type of alpha : <class 'float'>
type of param : torch.float32
type of alpha : <class 'float'>
type of param : torch.float32
type of alpha : <class 'float'>
type of param : torch.float32
type of alpha : <class 'float'>
type of param : torch.float32
type of alpha : <class 'float'>
type of param : torch.float32
type of alpha : <class 'float'>
type of param : torch.float32
type of alpha : <class 'float'>
type of param : torch.int64
type of alpha : <class 'float'>**

How can I solve this?

**Comment by dariopavllo** [comment]
Fixed in https://github.com/dariopavllo/convmesh/commit/27cdbf2b6ef0c7e39baa4a29cba9e4ebc5a9e29e!

**Comment by yuta-tech** [comment]
I confirmed it. And the error was solved!
Thank you for your prompt response.
